create table public.todos (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  task text not null,
  completed boolean not null default false,
  owner uuid null,
  constraint todos_pkey primary key (id),
  constraint todos_owner_fkey foreign KEY (owner) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;